name: Deployment - Reusable Workflow

on:
    workflow_call:
        secrets:
            k8s-kubeconfig:
                required: true
            mongodb-password:
                required: true
        inputs:
            mongo_uri:
                required: true
                type: string
            kubectl-version:
                description: Provide the required Kubectl version
                required: false
                default: v1.26.0
                type: string
            k8s-manifest-dir:
                description: Directory containing kubernetes manifest files
                required: true
                default: kubernetes/
                type: string
            environment:
                description: Provide the deployment environment
                default: dev
                required: true
                type: string
        outputs:
            application-url:
                value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL }}

jobs:
    reuse-deploy:
        environment:
            name: ${{ inputs.environment }}
            url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
        runs-on: ubuntu-latest
        outputs:
            APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Install kubectl CLI
              uses: azure/setup-kubectl@v4.0.0
              with:
                version: ${{ inputs.kubectl-version }}

            # - name: Setup Kubernetes context
            #   uses: azure/k8s-set-context@v4.0.0
            #   with:
            #     method: kubeconfig
            #     kubeconfig: ${{ secrets.k8s-kubeconfig }}
            
            # - name: Fetch Kubernetes Cluster Details
            #   run: |
            #     kubectl version --short -oyaml
            #     echo -----------------------
            #     kubectl get nodes

            # - name: Save Ingress IP as a GITHUB Environment variable
            #   run: |
            #     echo "INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -ojsonpath=".status.loadBalancer.ingress[0].ip")" >> $GITHUB_ENV

            - name: Replace tokens in manifest files
              uses: cschleiden/replace-tokens@v1.3
              with:
                tokenPrefix: '${'
                tokenSuffix: '}'
                files: '["${{ inputs.k8s-manifest-dir }}*.yaml"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE }}
                REPLICAS: ${{ vars.REPLICAS}}
                IMAGE: ${{ vars.DOCKERHUB_USERNAME}}/solar-system:${{ github.sha }}
                # INGRESS_IP: ${{ env.INGRESS_IP }}
                INGRESS_IP: my-app

            - name: Check files
              run: |
                cat ${{ inputs.k8s-manifest-dir }}*.yaml

            - name: Create DB creds secret
              run: |
                kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
                --from-literal=MONGO_URI=${{ inputs.mongo_uri }} \
                --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
                --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password }} \
                --save-config \
                --dry-run=client \
                -o yaml

            # - name: Deploy to Dev Env
            #   run: |
            #     kubectl apply -f ${{ inputs.k8s-manifest-dir }}*.yaml

            - name: Set App Ingress Host URL
              id: set-ingress-host-address
              run: |
                echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath=".items[0].spec.tls[0].hosts[0]")" >> $GITHUB_OUTPUT
